# Basics of python and numpy

Outline

- Import statements
- Printing
- Variables and types
- Basic arithmetic
- NumPy Arrays: Vectors
- Numpy Arrays: Matrices
- Dot products between vectors
- Matrix-vector products
- Matrix-matrix products
- Hermitian matrices
- Eigenvalues and eigenvectors
- Commutators


## Import statements
Python has intrinsic functionality as a programming language, but there are also many special-purpose libraries that are helpful.  Here we will use the library `numpy` for numerical computing.

In [1]:
import numpy as np
from numpy import linalg as la

## Printing
The way to communicate between the computer and you is through different types of print statements.  These can display data to the screen, or write data to a file.  We can also plot data, which we will see in a future lesson.  For now, we will use the print statement to write the canonical first program: Hello World

The syntax for printing the string "Hello World!" is

`print("Hello World!")`

In [2]:
print("Ruby")

Ruby


## Variables and types
Much of the power of programming languages lies in the ability to perform complicated operators on data.  Data used throughout a program is stored in variables.  We can use *most* any name we want for variables, though there are some best practices:  we should try to use descriptive names when possible, we should use lower case letters, we should separate words in compound names with an underscore.  We **cannot** use certain words that correspond to built-in functions in python, like `print`, `for`, `while`, `if`, `elif`, `else`, `type` to name a few commmon ones.

We can also store many types of data as variables.  Data types in python include `int` (integers), `floats` (numbers with decimal places), `str` (strings of characters, e.g. words), `complex` (complex numbers), `bool` (boolean True/False).

In [3]:
# the following variable is a string
my_message = "Hello World!"

# thie following variable is an int
my_integer = 1

# the following variable is a float
my_float = 2.1223

# insert code to print my_message
print(my_message)
print(type(my_message))
# insert code to print my_integer
print(my_integer)
print(type(my_integer))
# insert code to print my_float
print(my_float)
print(type(my_float))




# new_int = int(my_message)
# print(type(new_int))

Hello World!
<class 'str'>
1
<class 'int'>
2.1223
<class 'float'>


## Basic Arithmetic
We can perform addition, substraction, division, and multiplication using the
`+`, `-`, `/`, `*` operators.  Try using these operations with the variables that are pre-defined for you below

In [4]:
my_float_1 = 3.12
my_float_2 = 2.11

my_int_1 = 2
my_int_2 = 5

my_string_1 = "string 1"
my_string_2 = "string 2"

# insert code to add my_float_1 to my_float_2; print result
my_float_3 = my_float_1 + my_float_2
print(my_float_3)
# insert code to add my_int_1 to my_int_2; print result

# insert code to add my_string_1 to my_string_2; print result
my_string_3 = my_string_1 + my_string_1
print(my_string_3)

# insert code to substract my_float_1 from my_float_2; print result
my_float_3 = my_float_2 - my_float_1 
print(my_float_3)

# insert code to subtract my_int_1 from my_int_2; print result
my_int_3 = my_int_2 - my_int_1
print(my_int_3)

# insert code to multiply my_float_1 by my_float_2; print result
my_float_4 = my_float_2 * my_float_1 
print(my_float_4)

# insert code to multiply my_int_1 by my_int_2; print result
my_int_4 = my_int_2 * my_int_1
print(my_int_4)

# insert code to divide my_float_1 by my_float_2; print result
my_float_5 = my_float_1 / my_float_2 
print(my_float_5)

# insert code to divide my_int_1 by my_int_2; print result
my_int_5 = my_int_1 / my_int_2
print(my_int_5)


5.23
string 1string 1
-1.0100000000000002
3
6.5832
10
1.4786729857819907
0.4


## Numpy arrays: Vectors
Numpy arrays are special types of variables that can make use of different mathematical operation in the numpy library.  We will see that a lot of linear algebra operations can be performed with numpy arrays using very simple syntax.  Numpy arrays can have an arbitrary number of dimensions, but we will use 2-dimensional numpy arrays with
a single column and multiple rows to denote a column vector.  We can take the transpose of these numpy arrays to represent a row vector.  

Let's use as an example the basis states of spin kets that we have seen / will see soon in lecture:

\begin{equation}
|\chi_{\alpha}^{(z)} \rangle=
\begin{bmatrix}
  1 \\
  0 \\
\end{bmatrix}
\end{equation}


\begin{equation}
|\chi_{\beta}^{(z)}\rangle =
\begin{bmatrix}
  0 \\
  1 \\
\end{bmatrix}
\end{equation}

$|\chi_{\alpha}^{(z)}\rangle$ can be formed using the following syntax:
`ket_alpha = np.array([[1],[0]])`

We can get the number of rows and number of columns (the shape) of this vector using `np.shape(ket_alpha)`.

In [29]:
# insert code to assign ket chi_alpha
ket_alpha =np.array([[1],[0]])

# insert code to assign ket chi_beta
ket_beta = np.array([[0],[1]])

# insert code to print both kets
print(ket_alpha)
print(ket_beta)

# compute and print the shape of bra_alpha
shape_alpha = np.shape(ket_alpha)
shape_beta = np.shape(ket_beta)

print(shape_alpha)
print(shape_beta)

[[1]
 [0]]
[[0]
 [1]]
(2, 1)
(2, 1)


We can form the bras corresponding to these kets by taking the complex conjugate and transpose of the column vectors we have just formed.  The result will be row vectors, keeping the correspondence to the "bra" - "ket" convention.

$$ \langle \chi_{\alpha}^{(z)}| = |\chi_{\alpha}^{(z)}\rangle ^{\dagger} = [1^* \: 0^*] $$

$$ \langle \chi_{\beta}^{(z)}| = |\chi_{\beta}^{(z)}\rangle ^{\dagger} = [0^* \: 1^*]$$

This operation can be computed using the following syntax:
`bra_alpha = ket_alpha.conj().T`

You can compute the shape of the bras in the same way as you used for the kets; take note of how the shape changes.

In [6]:
# insert code to assign bra chi_alpha as adjoint of ket chi_alpha
bra_alpha = ket_alpha.conj().T
print(bra_alpha)

# insert code to assign bra chi_beta as adjoint of ket chi_beta

bra_beta = ket_beta.conj().T
print(bra_beta)

# compute and print the shape of bra_alpha
shape_alpha_bra = np.shape(bra_alpha)
shape_beta_bra = np.shape(bra_beta)

print(shape_alpha_bra)
print(shape_beta_bra)

[[1 0]]
[[0 1]]
(1, 2)
(1, 2)


## Computing the bra-ket
We can view the bra-ket (also called the inner product between the bra and the ket) as a test of how much the state in the bra projects on to the state in the ket.  The answer can be anywhere between 0 (the states do not project onto each other at all, they are orthogonal states, they do not overlap at all) to 1 (these states perfectly project onto one another, they have perfect overlap, they are identical states).  We know (or will soon learn) that the spin states are orthonormal states: they have perfect overlap with themselves and zero overlap with each other.  This is codified with the following mathematical statements

$$\langle \chi_n^{(z)} | \chi_m^{(z)}\rangle = \delta_{nm} $$

where where have used the Kronecker delta function $\delta_{nm} = 0$ if $n\neq m$ and $\delta_{nm} = 1$ if $n=m$.

With their vector representations, we can compute the bra-ket using the dot product as follows:
`bra_ket_aa = np.dot(bra_alpha, ket_alpha)`


In [7]:
# insert code to compute <alpha|alpha>
inner_product_aa = np.dot(bra_alpha, ket_alpha )

# insert code to compute <alpha|beta>
inner_product_ab = np.dot(bra_alpha, ket_beta )

# insert code to compute <beta|alpha>
inner_product_ba = np.dot(bra_beta, ket_alpha )

# insert code to compute <beta|beta>
inner_product_bb = np.dot(bra_beta, ket_beta )

# print all bra-kets to make sure they behave as expected
print("<alpha|alpha> = ", inner_product_aa)
print("<alpha|beta> = ", inner_product_ab)
print("<beta|alpha> = ", inner_product_ba)
print("<beta|beta> = ", inner_product_bb)


inner_product_ketbra = np.dot(ket_beta, bra_beta )


# Always bra on left in bracket and ket on left (bra, ket)
#try with more examples 


<alpha|alpha> =  [[1]]
<alpha|beta> =  [[0]]
<beta|alpha> =  [[0]]
<beta|beta> =  [[1]]


## Numpy arrays: Matrices
We will use 2-dimensional numpy arrays with
a an equal number of rows and columns to denote square matrices.  
Let's use as an example matrix representation of the $\hat{S}_z$ operator that we have seen / will see soon in lecture:

\begin{equation}
\mathbb{S}_z = \frac{\hbar}{2}
\begin{bmatrix}
  1 & 0 \\
  0 & -1 \\
\end{bmatrix}
\end{equation}


$\mathbb{S}_z$ can be formed using the following syntax:
`Sz = hbar / 2 * np.array([[1, 0],[0, -1]])`

You can take the shape of the Sz matrix as before; take note of how its shape compares to the shape of the bras and kets.

**Note** The value of $\hbar$ in atomic units is 1.

In [8]:
# define hbar in atomic units
hbar = 1

# insert code to define the Sz matrix
Sz = hbar/2 * np.array([[1 , 0], [0 ,-1]])


# insert code to print the matrix
print(Sz)

# print shape of Sz
shape_Sz = np.shape(Sz)
print(shape_Sz)

[[ 0.5  0. ]
 [ 0.  -0.5]]
(2, 2)


## Matrix-vector products
An important property of the basis kets $|\chi_{\alpha}^{(z)} \rangle$ and $|\chi_{\beta}^{(z)} \rangle$ is that they were eigenstates of the $\hat{S}_z$ operator satisfying

$$ \hat{S}_z |\chi_{\alpha}^{(z)} \rangle = +\frac{\hbar}{2}|\chi_{\alpha}^{(z)} \rangle $$

$$ \hat{S}_z |\chi_{\beta}^{(z)} \rangle = -\frac{\hbar}{2}|\chi_{\beta}^{(z)} \rangle $$.

This property should be preserved with the matrix and vector representations of these operators and states, respectively.  We can confirm this by taking the matrix-vector product between $\mathbb{S}_z$ and the vectors corresponding to these basis kets using the syntax

`Sz_ket_a = np.dot(Sz, ket_alpha)`


We can inspect them to see if this relationship holds, but see if you can figure an alternative way to confirm the relationship holds.

In [9]:
# compute product of Sz and ket_alpha
Sz_ket_a = np.dot(Sz , ket_alpha)

# compute product of Sz and ket_beta
Sz_ket_b = np.dot(Sz , ket_beta)

# print product of Sz and ket_alpha
print(Sz_ket_a)

# print product of Sz and ket_beta
print(Sz_ket_b)


#Here, ket_alpha and ket_beta are eigen vectors of Sz and h/2 and -h/2 are eigenvalues of these eigen vectors. 
# If we perform ket vectors on Sz matrix, it'll either increase the magnitude or decrease the magnitude but the vector by some
# number but it points in same direction.

[[0.5]
 [0. ]]
[[ 0. ]
 [-0.5]]


## Hermitian matrices
<font color='red'>The matrix representations of operators in quantum mechanics are called Hermitian matrices<font>.  Hermitian matrices have the special relationship that they are equal to their adjoint (i.e., their complex conjugate transpose).  

You can confirm that $\mathbb{S}_z$ is Hermitian by the following syntax:

`Sz_adjoint = Sz.conj().T`
`print(np.allclose(Sz_adjoint, Sz))`

where the first line computes the adjoint of $\mathbb{S}_z$ and stores it to a variable `Sz_adjoint` and
the second line prints the result of comparing all elements of `Sz_adjoint` to `Sz`.  The return value of `True` will
indicate that `Sz_adjoint` is numerically equal to `Sz`.

In [10]:
# Confirm Sz is Hermitian here
Sz_adjoint =np.copy(Sz.conj().T)
print(Sz_adjoint)

Sz_adjoint[0,0] = Sz_adjoint[0,0] + 1e-2 

# Allclose() function 
print(np.allclose(Sz_adjoint, Sz, 1e-6,1e-6))

#all close will give flase on adding something to its first element. 

[[ 0.5  0. ]
 [ 0.  -0.5]]
False


## Eigenvalues and eigenvectors
**An important property of Hermitian matrices is that their eigevalues are real numbers**.  In quantum mechanics, we associate the possible outcomes of measurements with the eigenvalues of Hermitian operators corresponding to the observable being measured.  In this notebook, we have been talking about the observable of spin angular momentum, which is a vector quantity. We have been specifically looking at the operators and eigenstates related to the z-component of spin angular momentum, denoted $S_z$. We have seen that this operator has two eigenstates,
$|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$ with associated eigenvalues $\frac{\hbar}{2}$ and $-\frac{\hbar}{2}$, which are both real numbers.  

These relationships are preserved when we use the matrix - vector representation of operators and eigenstates.  In general, an eigenvalue equation with matrices and vectors satisfies

$$ \mathbb{M} \bf{x} = \lambda \bf{x} $$

where $\lambda$ is an eigenvalue (which is a number) and $\bf{x}$ is an eigenvector.  One way of interpreting these equations is to say that the action of a matrix on its eigenvectors is simply to scale the magnitude of the vector by a number (specifically, scale it by its eigenvalue).  This is a very special situation, because typically speaking, when a vector is multiplied by a matrix, the result is a new vector that points along a new direction and has a different magnitude.  For a lovely explanation with graphical illustrations, please consult [this vide](https://youtu.be/PFDu9oVAE-g).  In fact, the entire 3b1b series on linear algebra is wonderful!

We have already seen that vectors associated with the basis kets $|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$ obey this relationship with $\mathbb{S}_z$.  What we will now do, is consider the matrices associated with the spin angular momentum components along $x$ and $y$.  We will first see that the
basis kets $|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$ are not eigenvectors of $\mathbb{S}_x$ and $\mathbb{S}_y$.  We will then use numpy's linear algebra sub-library to compute the eigenvalues and eigenvectors of these matrices, which will turn out to be linear combinations of $|\chi_{\alpha}^{(z)}\rangle$ and $|\chi_{\beta}^{(z)}\rangle$.  

### Build matrix form of $\mathbb{S}_x$ and $\mathbb{S}_y$
The operator $\hat{S}_x$ has the matrix form
\begin{equation}
\mathbb{S}_x = \frac{\hbar}{2}
\begin{bmatrix}
  0 & 1 \\
  1 & 0 \\
\end{bmatrix}
\end{equation}
and the operator $\hat{S}_y$ has the matrix form
\begin{equation}
\mathbb{S}_y = \frac{\hbar}{2}
\begin{bmatrix}
  0 & -i \\
  i & 0 \\
\end{bmatrix}.
\end{equation}

**Hint** The imaginary unit $i = \sqrt{-1}$ can be accessed as `1j` in python.

In [11]:
# insert code to build Sx
S_x = hbar/2 * np.array([[0,1],[1,0]])


# insert code to build Sy
S_y = (hbar/2) * np.array([[0,-1j],[1j,0]])

# print Sx
print(S_x)

# print Sy
print(S_y)

[[0.  0.5]
 [0.5 0. ]]
[[0.+0.j  0.-0.5j]
 [0.+0.5j 0.+0.j ]]


### Take matrix-vector product of $\mathbb{S}_x$ and $\mathbb{S}_y$ with the basis kets
Just as we did with $\mathbb{S}_z$, take the following matrix-vector products:
$$ \mathbb{S}_x |\chi_{\alpha}^{(z)}\rangle $$
$$ \mathbb{S}_x |\chi_{\beta}^{(z)}\rangle $$
$$ \mathbb{S}_y |\chi_{\alpha}^{(z)}\rangle $$
$$ \mathbb{S}_y |\chi_{\beta}^{(z)}\rangle $$

**Question 1:** After inspecting the results of each matrix-vector product, do you think the basis kets are eigenstates of
$\mathbb{S}_x$ and $\mathbb{S}_y$?  Explain your reasoning. <br>
**Answer** : From the rsult, it looks like basis kets are eigenstates of $\mathbb{S}_x$ and $\mathbb{S}_y$. Because after the operation of $\mathbb{S}_x$ and $\mathbb{S}_y$ on kets, it gives a scaler value mutlipy by ket itself which means scaler is eiegnvalue and kets are eigenvectors. 

**Question 2:** What is the shape of the result of each matrix-vector product?<br>
**Answer**: The shape of the matrix product are (2,1) for all.

In [12]:
# compute product of Sx and ket_alpha and store to Sx_ket_a; print it
Sx_ket_a = np.dot(S_x,ket_alpha)
print(Sx_ket_a)

# compute product of Sx and ket_beta and store to Sx_ket_b; print it
Sx_ket_b = np.dot(S_x, ket_beta)
print(Sx_ket_b)

# compute product of Sy and ket_beta and store to Sy_ket_b; print it
Sy_ket_b = np.dot(S_y, ket_beta)
print(Sy_ket_b)

# compute product of Sy and ket_alpha and store to Sy_ket_b; print it
Sy_ket_a = np.dot(S_y, ket_alpha)
print(Sy_ket_a)

print(np.shape(Sx_ket_a))
print(np.shape(Sx_ket_b))
print(np.shape(Sy_ket_a))
print(np.shape(Sy_ket_b))

[[0. ]
 [0.5]]
[[0.5]
 [0. ]]
[[0.-0.5j]
 [0.+0.j ]]
[[0.+0.j ]
 [0.+0.5j]]
(2, 1)
(2, 1)
(2, 1)
(2, 1)


### Use `eigh()` to compute the eigenvectors and eigenvalues of $\mathbb{S}_x$ and $\mathbb{S}_y$
Numpy has a linear algebra library that can compute eigenvalues and eigenvectors of Hermitian matrices that is called using the syntax
`eigh()` is gives best results for Hermitian matrices only. 


`eigenvalues, eigenvectors = la.eigh(M)`

where `eigenvalues` will store all of the eigenvectors and `eigenvectors` will store all the eigenvectors.  
Use this method to compute the eigenvalues and eigenvectors of $\mathbb{S}_x$ and $\mathbb{S}_y$.

**Note** A namedtuple with the following attributes:
eigenvectors[:, i] is the normalized eigenvector corresponding to the eigenvalue eigenvalues[i].


**Question 3:** What is the shape of the vals_x?  What is the shape of vecs_x? <br>
**Answer**: The shape of Eigenvalues of Sx (Vals_Sx) is (2,) while for eigenvectors of Sx (vecs_Sx) is (2,2).<br>
**Question 4:** Do these matrices have the same eigenvalues as $\mathbb{S}_z$?  Do they have the same eigenvectors as $\mathbb{S}_z$? <br>
**Answer**:Eigenvalues of Sx, Sy and Sz are same but eigenvectors are different from each other and also from Sz.

In [13]:
Vals_Sz, Vects_Sz = la.eigh(Sz)
print(f"Eigenvalues of Sz are : {Vals_Sz}")
print(f"Eigenvectors of Sz are :{Vects_Sz}")

# compute eigenvectors and eigenvalues of Sx, store them to vals_x, vecs_x
Vals_Sy, Vects_Sy = la.eigh(S_y)
print(f"Eigenvalues of Sy are : {Vals_Sy}")
print(f"Eigenvectors of Sy are :{Vects_Sy}")


# compute eigenvectors and eigenvalues of Sy, store them to vals_y, vecs_y
Vals_Sx, Vects_Sx = la.eigh(S_x)
print(f"Eigenvalues of Sx are :{Vals_Sx}")
print(f"Eigenvectors of Sx are :{Vects_Sx}")


# print shape of vecs_x
print(np.shape(Vals_Sy))
print(np.shape(Vals_Sx))

print(np.shape(Vects_Sy))
print(np.shape(Vects_Sx))



Eigenvalues of Sz are : [-0.5  0.5]
Eigenvectors of Sz are :[[0. 1.]
 [1. 0.]]
Eigenvalues of Sy are : [-0.5  0.5]
Eigenvectors of Sy are :[[-0.70710678+0.j         -0.70710678+0.j        ]
 [ 0.        +0.70710678j  0.        -0.70710678j]]
Eigenvalues of Sx are :[-0.5  0.5]
Eigenvectors of Sx are :[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
(2,)
(2,)
(2, 2)
(2, 2)


### Expectation values
Another important operation in quantum mechanics is the computation of an expectation value, which can be written as a bra-ket sandwiching an operator:

$$ \langle n | \hat{O}| m \rangle. $$

The result will depend on what $\hat{O}$ does to $|m\rangle$, and how the resulting ket projects upon $\langle n|$.

We can use the different eigenvectors from our last block as kets, and their adjoints as bras, along with the matrix form of the operators to compute these operations.  

`ket_x_0 = vecs_x[:,0]`

`bra_x_0 = ket_x_0.conj().T`

`expectation_value = np.dot(bra_x_0, np.dot(Sx, ket_x_0))`


NOTE: The operation of a matrix on a ket will give a ket vector and then, operation of a ket on bra vector will be a number.

In [14]:
ket_x_1 = Vects_Sx[:,0]
print(ket_x_1)

[-0.70710678  0.70710678]


**Question 5:** If we associate $|\chi_{\alpha}^{(x)}\rangle$ with `vec_x[:,1]`, what is the expectation value corresponding to $\langle \chi_{\alpha}^{(x)} | \hat{S}_x | \chi_{\alpha}^{(x)} \rangle $? <br>

**Answer** : The expectation value of $\langle \chi_{\alpha}^{(x)} | \hat{S}_x | \chi_{\alpha}^{(x)} \rangle $ is  0.4999999999999999.


In [15]:
ket_alpha_x = Vects_Sx[:,1]
bra_alpha_x = ket_alpha_x.conj().T 
expectation_value_x = np.dot(bra_alpha_x, np.dot(S_x, ket_alpha_x))
print(f" Expectation value of ket_alpha with Sx and bra_alpha is {expectation_value_x}")
print(ket_alpha_x)
print(Vects_Sx)

 Expectation value of ket_alpha with Sx and bra_alpha is 0.4999999999999999
[0.70710678 0.70710678]
[[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]


**Question 6:** If we associate $|\chi_{\alpha}^{(y)}\rangle$ with `vec_y[:,1]`, what is the expectation value corresponding to $\langle \chi_{\alpha}^{(y)} | \hat{S}_z | \chi_{\alpha}^{(y)} \rangle $? <br>
**Answer** : THe expectation value of $\langle \chi_{\alpha}^{(y)} | \hat{S}_z | \chi_{\alpha}^{(y)} \rangle $ is  0j.


In [16]:
ket_alpha_y = Vects_Sy[:,1]
bra_alpha_y = ket_alpha_y.conj().T 
expectation_value_y = np.dot(bra_alpha_y, np.dot(Sz, ket_alpha_y))
print(f" Expectation value of ket_alpha with Sx and bra_alpha is {expectation_value_y}")

 Expectation value of ket_alpha with Sx and bra_alpha is 0j


In [17]:
# Compute <alpha_x|Sx|alpha_x>; print the result
ket_x_0 = Vects_Sx[:,0]
bra_x_0 = ket_x_0.conj().T
expectation_value_x = np.dot(bra_x_0, np.dot(S_x, ket_x_0))
print(expectation_value_x)



# Compute <alpha_y|Sz|alpha_y>; print the result
ket_y_0 = Vects_Sy[:,0]
bra_y_0 = ket_y_0.conj().T
expectation_value_y = np.dot(bra_y_0, np.dot(S_y, ket_y_0))
print(expectation_value_y)


-0.4999999999999999
(-0.4999999999999999+0j)


### Commutators
We will learn later in 3141 about generalized uncertainty relations.  An important mathematical operation in formulation of uncertainty relations is the commutator, which can be taken between two operators or two matrices representing operators.  The commutator between operators $\hat{A}$ and $\hat{B}$ can be written as

$$ [\hat{A}, \hat{B}] = \hat{A} \hat{B} - \hat{B} \hat{A} $$,
and the same relation holds for the matrix form of the operators.
A few things we should note about commutators right now is:
1. If the equation above goes to zero, we say the operators commute
2. If the equation above is not zero, we say the operators do not commute
3. Commuting operators share the same set of eigenstates, and their matrix representations share the same set of eigenvectors
4. Commuting operators are related to special pairs of observables that are called compatibile observables; we can simultaneously know the value of compatible observables with unlimited precision
5. Operators that do not commute correspond to pairs of observables that are not compatible, there are strict limits on the precision with which we can simultaneously know the values of incompatible observables.

The spin operators, and their corresponding matrices, obey the following commutation relations:

$$[\hat{S}_x, \hat{S}_y] = i\hbar \hat{S}_z $$

$$[\hat{S}_y, \hat{S}_z] = i\hbar \hat{S}_x $$

$$[\hat{S}_z, \hat{S}_x] = i\hbar \hat{S}_y $$

**Question 7:** Are the observables corresponding to $\hat{S}_x$ compatible with the observables corresponding to $\hat{S}_y$?  Explain your reasoning.<br>
**Answer** : The observables corresponding to $\hat{S}_x$ are not compatible with the observables corresponding to $\hat{S}_y$ because commutation of $[\hat{S}_x, \hat{S}_y] = i\hbar \hat{S}_z $ is not zero. The measurements of observables of $\hat{S}_x$ will effects the measurements on observables related to $\hat{S}_y$. <br> 

**Question 8:** Confirm that the matrices $\mathbb{S}_x$, $\mathbb{S}_y$, and $\mathbb{S}_z$ obey the same commutation relations as shown above.  The syntax for computing matrix products is either `np.dot(A,B)` or equivalently `A @ B`:

`SxSy = np.dot(Sx, Sy)`

is the same as

`SxSy = Sx @ Sy`



In [18]:

# compute commutator of Sx and Sy and compare to i*hbar*Sz
SxSy = np.dot(S_x,S_y)
print(f" Commutation of Sx and Sy is: \n {SxSy}")
Sz_new = 1j*hbar/2*Sz
print(f" Sz matrix is \n {Sz_new}")



# compute the commutator of Sy and Sz and compare to i*hbar*Sx
SySz = np.dot(S_y,Sz)
print(f" Commutation of Sy and Sz is \n {SySz}")
S_x_new = 1j*hbar/2*S_x
print(f" Sx matrix is \n {S_x_new}")

# compute the commutator of Sz and Sx and compare to i*hbar*Sy
SzSx = np.dot(Sz,S_x)
print(f" Commutation of Sz and Sy is \n {SzSx}")
S_y_new = 1j*hbar/2*S_y
print(f" Sy matrix is \n {S_y_new}")


#comparing all mtrices 

np.allclose(SxSy,Sz_new)
np.allclose(SySz,S_x_new)
np.allclose(SzSx,S_y_new)

 Commutation of Sx and Sy is: 
 [[0.+0.25j 0.+0.j  ]
 [0.+0.j   0.-0.25j]]
 Sz matrix is 
 [[ 0.+0.25j  0.+0.j  ]
 [ 0.+0.j   -0.-0.25j]]
 Commutation of Sy and Sz is 
 [[0.+0.j   0.+0.25j]
 [0.+0.25j 0.+0.j  ]]
 Sx matrix is 
 [[0.+0.j   0.+0.25j]
 [0.+0.25j 0.+0.j  ]]
 Commutation of Sz and Sy is 
 [[ 0.    0.25]
 [-0.25  0.  ]]
 Sy matrix is 
 [[ 0.  +0.j  0.25+0.j]
 [-0.25+0.j  0.  +0.j]]


True

In addition to Completing the questions included in the notebook, answer the following questions using Numpy within your Spin ½ notebook.  To submit this assignment, download your notebook as a .ipynb and email to jfoley19@charlotte.edu with the subject “Homework 2”.

The spin matrices we have seen can be written in terms of the Pauli matrices as follows:

\begin{align}
\mathbb{S}_x = \frac{\hbar}{2}\mathbf{\sigma}_x \\
\mathbb{S}_y = \frac{\hbar}{2}\mathbf{\sigma}_y \\
\mathbb{S}_z = \frac{\hbar}{2}\mathbf{\sigma}_z.
\end{align}

Among other things, the Pauli matrices play an important role in quantum information, and specifically comprise important [quantum gates](https://en.wikipedia.org/wiki/Quantum_logic_gate).

As one example, the so-called Hadamard gate can be written as 

\begin{equation}
\mathbb{H} = \frac{1}{\sqrt{2}} \left( \mathbf{\sigma}_x + \mathbf{\sigma}_z \right) \tag.
\end{equation}

**Question 9:** Demonstrate numerically that $\mathbb{H} |\chi_{\alpha}^{z}\rangle = |\chi_{\alpha}^{x}\rangle $
and that $\mathbb{H} |\chi_{\beta}^{z}\rangle = |\chi_{\beta}^{x}\rangle $





In [32]:
# Pauli matrices 
Sigma_x = 2* S_x

Sigma_y = 2* S_y

Sigma_z = 2*Sz

# computing H
H = 1/np.sqrt(2)*(Sigma_x + Sigma_z)

# computing opertaion of H on ket_alpha_z
H_ket_az = np.dot(H, ket_alpha)

np.allclose(H_ket_az, ket_alpha_x)


True

In [35]:
# computing opertaion of H on ket_beta_z
H_ket_bz = np.dot(H, ket_beta)

np.allclose(H_ket_bz, ket_x_1)

print(H_ket_bz)
print(ket_x_1)


[[ 0.70710678]
 [-0.70710678]]
[-0.70710678  0.70710678]


**Question 10:** Given the definition of the Hadamard gate, comment on if it is a Hermitian matrix or not.  If it is not Hermitian, does it have any other special properties?<br> 
**Answer** : The conjugate transpose of Hadamard matrix is same as Hamdamard matrix, which means it is Hermitian matrix. The main properties of Hamdamard matrix are : <br>
1. It is a unitary matrix and eigenvalues are real numbers. <br>
2. it is commutative matrix. 
3. it is also orthogonal. 
4. it is used in Quantum computing as logic gates for qubits. 